### ISSUE TITLE
Google Fonts QA report

### ISSUE THREAD

**Issue by m4rc1e** [carolinashort/mansalva#1]
## Fontbakery report

Fontbakery version: 0.7.9

<details>
<summary><b>[10] Mansalva-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsType.</summary>

* [com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype)
* 🔥 **FAIL** OS/2 fsType is a legacy DRM-related field.
In this font it is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.
No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.
Fonts with this setting indicate that they may be embedded and permanently installed on the remote system by an application.

 More detailed info is available at:
 https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x00B7 (MIDDLE DOT), 0x02DA (RING ABOVE), 0x201A (SINGLE LOW-9 QUOTATION MARK), 0x2044 (FRACTION SLASH) and 0x2212 (MINUS SIGN)

</details>
<details>
<summary>🔥 <b>FAIL:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache: 'http://www.apache.org/licenses/LICENSE-2.0' or Open Font License: 'http://scripts.sil.org/OFL'
 For a small set of legacy families the Ubuntu Font License 'https://www.ubuntu.com/legal/terms-and-policies/font-licence' may be acceptable as well.
When in doubt, please choose OFL for new font projects. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2019 Mansalva Project Carolina Short (https://github.com/carolinashort/mansalva)'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2019 Mansalva Project Carolina Short (https://github.com/carolinashort/mansalva)'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinAscent value should be equal or greater than 1112, but got 1111 instead [code: ascent]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: U.alt1	Contours detected: 1	Expected: 2
Glyph name: at	Contours detected: 1	Expected: 2
Glyph name: O	Contours detected: 1	Expected: 2
Glyph name: b	Contours detected: 1	Expected: 2
Glyph name: q	Contours detected: 1	Expected: 2
Glyph name: ordfeminine	Contours detected: 1	Expected: 2 or 3
Glyph name: Egrave	Contours detected: 3	Expected: 2
Glyph name: Eth	Contours detected: 1	Expected: 2
Glyph name: odieresis	Contours detected: 3	Expected: 4
Glyph name: oslash	Contours detected: 2	Expected: 3
Glyph name: thorn	Contours detected: 3	Expected: 2
Glyph name: uniE0FF	Contours detected: 1	Expected: 7
Glyph name: uniF8FF	Contours detected: 7	Expected: 2 or 3
Glyph name: arrowup	Contours detected: 2	Expected: 1
Glyph name: arrowboth	Contours detected: 2	Expected: 1

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 6 | 4 | 70 | 8 | 71 |
| 0% | 4% | 3% | 44% | 5% | 45% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

## Diff images: [mansalva_qa.zip](http://35.188.158.120/media/0421f27e-0d3a-459c-8576-3a9476ea6076/mansalva_qa.zip)

**Comment by carolinashort** [comment]
Thanks Marc!

Do I need to fix all issues and submit again?

**Comment by m4rc1e** [comment]
Just let me know once you've fixes the issues and updated the fonts in the repo. I will submit them to Google Fonts.

**Comment by carolinashort** [comment]
Hi Marc,

I’ve fixed several issues of Mansalva, however I keep getting a couple of FAIL and 5 WARN that I am not sure if they are important, and I couldn’t fix
I’ve updated the font in the repo. Please let me know if this is OK, or if I need to work on something else.

Thanks,
Carolina


- · - · - · - · - · - · - · -
Carolina Short
Senior Tutor
Department of Computer Science |  Faculty of Computing and Mathematical Sciences
University of Waikato

**Comment by m4rc1e** [comment]
Don't worry about the non hinted font FAIL.

To fix the license FAIL, add the following to the font's customParameters:

license:
This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL


licenseURL:
http://scripts.sil.org/OFL


<img width="1371" alt="Screenshot 2019-08-28 at 09 47 55" src="https://user-images.githubusercontent.com/7525512/63840509-1611c580-c979-11e9-9af7-c07bed98340d.png">

**Comment by carolinashort** [comment]
Done! Thanks so much for your help!
I’ve looked at a dozen fonts to see what they had for licenseURL since that was the mistake in Fontbakery, and wasn’t able to fix it ;)

**Comment by m4rc1e** [comment]
Thank you for your cooperation. The fonts have passed so I have created a pr in google/fonts https://github.com/google/fonts/pull/2142

**Comment by carolinashort** [comment]
Great news Mac, Thank you!

- · - · - · - · - · - · - · -
Carolina Short
Senior Tutor
Department of Computer Science |  Faculty of Computing and Mathematical Sciences
University of Waikato
