### ISSUE TITLE
Numeros

### ISSUE THREAD

**Issue by fedekrum** [carolinashort/mansalva#2]
Hola Carolina.
Me equivoco o nos conocemos de Interlink BBS? Estoy seguro que si !! hace muchos años.
Me encanto esta tipo. Una pregunta..... tenes planes de hacer variantes de los numeros?
cuando tenes numeros como 111000 la tipo pierde esa magia que tiene al tener variantes.
Un abrazo y felicitaciones

**Comment by carolinashort** [comment]
Hola Federico,
¿Como estas tanto tiempo? Me acuerdo de vos de Interlink, cuántos años, cuántos cambios, no?
Gracias por tus comentarios sobre Mansalva. Voy a tener en cuenta lo de los números, es cierto que si usas varios números iguales se pierde la idea de manuscrita. Lo voy a incorporar en nuevas versiones.
Saludos!
Carolina

**Comment by carolinashort** [comment]
Subi una nueva version con alternates para los números ;)

**Comment by fedekrum** [comment]
> Subi una nueva version con alternates para los números ;)

Lo hiciste !!!! Genial 
Gracias !

**Comment by carolinashort** [comment]
;)

Ngā mihi,

- · - · - · - · - · - · - · -
Carolina Short
Lecturer
Department of Design | School of Computing and Mathematical Sciences
University of Waikato
