### ISSUE TITLE
Doesn't support Romanian language.

### ISSUE THREAD

**Issue by KevinSzabo** [carolinashort/mansalva#6]
Hi, I love this font and I was so happy that I found it for my first branding project but then I realized that it lacks Romanian letters & diacritical marks. I really hope you will consider adding this feature to this amazing font. Thank you !

Also, good job, this is how handwritten fonts should look like!

**Comment by carolinashort** [comment]
Thanks for your comments! Please check latest version of Mansalva as I have expanded and included support to all/most latin languages. Also, let me know if there are any flaws or mistakes or missing characters.
